<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-K4PK96U" failures="2" tests="5" name="Create Customer API Test" time="4.181" errors="0" timestamp="2023-02-24T11:17:15 IST">
  <testcase classname="com.home.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithInValidSecretkey" time="3.245">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.home.APITestingFramework.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretkey(CreateCustomerTest.java:44)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretkey -->
  <testcase classname="com.home.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithInValidSecretkey" time="3.245">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.home.APITestingFramework.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretkey(CreateCustomerTest.java:44)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretkey -->
  <testcase classname="com.home.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretkey" time="0.595"/>
  <testcase classname="com.home.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretkey" time="0.596"/>
  <testcase classname="com.home.APITestingFramework.testcases.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretkey" time="0.799"/>
</testsuite> <!-- Create Customer API Test -->
